/* ============================================================
   Utah Bucket List — data
   One row per place/experience. `section` maps to SECTIONS below.
   `done: true` items are pre-checked on first load only (seed data);
   after that, everything lives in localStorage.
   ============================================================ */

const TRIP_START = "2026-09-01";
const TRIP_END = "2027-06-30";

const SECTIONS = [
  {
    key: "now",
    label: "Do This Now",
    dates: "Time-sensitive · Sept 2026",
    icon: "bolt",
    theme: "rust",
    intro: "Windows that close fast — reservations, permits, once-a-year events.",
  },
  {
    key: "fall",
    label: "Fall",
    dates: "Sept – Nov 2026",
    icon: "leaf",
    theme: "amber",
    intro: "Cooler air, red rock without the crowds, peak color in the canyons.",
  },
  {
    key: "winter",
    label: "Winter",
    dates: "Dec 2026 – Mar 2027",
    icon: "snow",
    theme: "teal",
    intro: "Snow season. You've hit the marquee resorts — here's the rest.",
  },
  {
    key: "spring",
    label: "Spring",
    dates: "Apr – May 2027",
    icon: "bloom",
    theme: "sage",
    intro: "Snowmelt hikes and high-elevation spots waking back up.",
  },
  {
    key: "summer",
    label: "Early Summer",
    dates: "June 2027",
    icon: "sun",
    theme: "gold",
    intro: "This window ends June 2027 — a couple of these peak a little later, so an early visit still catches part of it.",
  },
  {
    key: "anytime",
    label: "Anytime",
    dates: "No seasonal rush",
    icon: "compass",
    theme: "dusk",
    intro: "SLC culture, food, and far-flung corners of the state — fit these in wherever.",
  },
  {
    key: "done",
    label: "Already Checked Off",
    dates: "Already in the book",
    icon: "stamp",
    theme: "ink",
    intro: "Everything already crossed off, kept here for the record.",
  },
];

const ITEMS = [
  // ---------- Already done ----------
  {
    id: "done-snowsports",
    section: "done",
    title: "Snowboarding + skiing tour",
    meta: "Park City · Snowbird · Solitude · Brighton · Deer Valley",
    blurb: "Snowboarded four resorts and skied Deer Valley — the marquee Cottonwoods/Park City circuit.",
    tags: [],
    done: true,
  },
  {
    id: "done-moab",
    section: "done",
    title: "Moab / Arches National Park",
    meta: "~4 hrs from SLC",
    blurb: "Assuming this means Arches specifically — if you also caught Canyonlands or Dead Horse Point, you can skip those below.",
    tags: [],
    done: true,
  },
  {
    id: "done-bryce",
    section: "done",
    title: "Bryce Canyon National Park",
    meta: "~4 hrs from SLC",
    blurb: "Hoodoos and amphitheaters — one of the Mighty 5 down.",
    tags: [],
    done: true,
  },
  {
    id: "done-lakeblanche",
    section: "done",
    title: "Lake Blanche",
    meta: "Big Cottonwood Canyon",
    blurb: "A repeat-worthy alpine lake hike close to town.",
    tags: ["repeat"],
    done: true,
  },
  {
    id: "done-antelope",
    section: "done",
    title: "Antelope Island",
    meta: "Great Salt Lake",
    blurb: "Bison, causeway views, and the lake itself.",
    tags: [],
    done: true,
  },
  {
    id: "done-fifthwater",
    section: "done",
    title: "Fifth Water / Diamond Fork Hot Springs",
    meta: "Spanish Fork Canyon",
    blurb: "Natural hot springs hike, already crossed off.",
    tags: [],
    done: true,
  },
  {
    id: "done-sundance",
    section: "done",
    title: "Sundance Film Festival",
    meta: "Park City",
    blurb: "Great timing — 2026 was Sundance's final year in Utah before it relocates to Boulder, CO.",
    tags: [],
    done: true,
  },
  {
    id: "done-alpineloop",
    section: "done",
    title: "Alpine Loop in fall",
    meta: "American Fork / Provo Canyon",
    blurb: "A repeat-worthy fall color drive you've already done once.",
    tags: ["repeat"],
    done: true,
  },
  {
    id: "done-bearlake",
    section: "done",
    title: "Bear Lake weekend",
    meta: "~2 hrs, UT/ID border",
    blurb: "The turquoise water weekend trip, already banked.",
    tags: [],
    done: true,
  },

  // ---------- Do this now ----------
  {
    id: "now-temple",
    section: "now",
    title: "Salt Lake Temple public open house",
    meta: "Reservations open Sept 1, 2026 · 11:00am MDT",
    blurb: "Book via TempleSquare.org or the Temple Square app. Open house runs Apr 5 – Oct 1, 2027; the Church expects 3–5 million visitors, so free tickets (up to 6 per guest) will move fast. The temple has been closed for a seismic retrofit — this is a rare, limited window before it's rededicated.",
    tags: ["time-sensitive", "reservation"],
    done: false,
  },
  {
    id: "now-fair",
    section: "now",
    title: "Utah State Fair + Greek Festival",
    meta: "September · Salt Lake City",
    blurb: "Both land in SLC in September — the Greek Festival is Utah's largest ethnic festival.",
    tags: ["time-sensitive"],
    done: false,
  },
  {
    id: "now-speedweek",
    section: "now",
    title: "Bonneville Speed Week",
    meta: "August · Bonneville Salt Flats",
    blurb: "Runs every August. If you miss it in 2026, mark your calendar for early August 2027.",
    tags: ["time-sensitive", "annual"],
    done: false,
  },

  // ---------- Fall 2026 ----------
  {
    id: "fall-zion",
    section: "fall",
    title: "Zion National Park",
    meta: "~4.5 hrs · non-technical options",
    blurb: "Canyon Overlook Trail, the paved Riverside Walk, Emerald Pools, Watchman Trail. Cooler fall temps make this an ideal window.",
    tags: [],
    done: false,
  },
  {
    id: "fall-capitolreef",
    section: "fall",
    title: "Capitol Reef National Park",
    meta: "~3.5 hrs · near Torrey",
    blurb: "The most central, least-crowded of the Mighty 5. Fruita orchards (fall harvest), Hickman Bridge, Cohab Canyon — also one of Utah's best parks for fall color.",
    tags: [],
    done: false,
  },
  {
    id: "fall-canyonlands",
    section: "fall",
    title: "Canyonlands (Island in the Sky) + Dead Horse Point",
    meta: "~4 hrs · near Moab",
    blurb: "An easy add-on to a return Moab trip if Arches didn't cover these: Mesa Arch, Grand View Point, and one of the Southwest's most dramatic overlooks.",
    tags: [],
    done: false,
  },
  {
    id: "fall-foliage",
    section: "fall",
    title: "More fall foliage drives",
    meta: "Peak color late Sept – early Oct",
    blurb: "Beyond the Alpine Loop you already love: Big Cottonwood Canyon + Guardsman Pass, Nebo Loop (Mount Nebo Scenic Byway), Mirror Lake Highway, and Logan Canyon (~1.5 hrs).",
    tags: [],
    done: false,
  },
  {
    id: "fall-goblinvalley",
    section: "fall",
    title: "Goblin Valley + Little Wild Horse Canyon",
    meta: "~3.5 hrs · certified Dark Sky park",
    blurb: "Freely wander mushroom-shaped hoodoos, then walk a non-technical slot canyon narrows. Worth a night under the stars.",
    tags: [],
    done: false,
  },

  // ---------- Winter 2026-27 ----------
  {
    id: "winter-alta",
    section: "winter",
    title: "Ski Alta",
    meta: "Skier-only · ~548in avg snowfall",
    blurb: "Since you already ski at Deer Valley, Alta's skier-only terrain (no snowboards) is fair game — among the snowiest resorts in the US.",
    tags: [],
    done: false,
  },
  {
    id: "winter-snowmobile",
    section: "winter",
    title: "Snowmobiling in the Uintas",
    meta: "~1 hr · Mirror Lake / Mill Hollow / Strawberry",
    blurb: "250+ miles of groomed trail. This is the one item on your interest list that hasn't come up anywhere else yet.",
    tags: [],
    done: false,
  },
  {
    id: "winter-homestead",
    section: "winter",
    title: "Homestead Crater",
    meta: "Midway · ~45 min–1 hr · reservations required",
    blurb: "Swim in a 90–96°F geothermal spring inside a limestone dome.",
    tags: ["reservation"],
    done: false,
  },
  {
    id: "winter-mystic",
    section: "winter",
    title: "Mystic Hot Springs",
    meta: "Monroe · ~2.5 hrs",
    blurb: "Vintage clawfoot tubs — a different vibe from Fifth Water.",
    tags: [],
    done: false,
  },
  {
    id: "winter-templelights",
    section: "winter",
    title: "Temple Square Christmas lights + Tabernacle Choir concert",
    meta: "Late Nov – Jan 1",
    blurb: "The lights display plus the Tabernacle Choir's free Christmas concert.",
    tags: [],
    done: false,
  },
  {
    id: "winter-newresort",
    section: "winter",
    title: "A new resort for variety",
    meta: "Powder Mountain or Snowbasin · ~1–1.5 hrs",
    blurb: "Both are less crowded than the Cottonwoods, if you want a change of pace from your usual spots.",
    tags: [],
    done: false,
  },

  // ---------- Spring 2027 ----------
  {
    id: "spring-cedarbreaks",
    section: "spring",
    title: "Cedar Breaks National Monument",
    meta: "Opens ~late May · certified Dark Sky",
    blurb: "A Bryce-like high-elevation amphitheater. Elevation-dependent, so check road status — it stays snowed in through spring in a normal snowpack year.",
    tags: [],
    done: false,
  },
  {
    id: "spring-calfcreek",
    section: "spring",
    title: "Lower Calf Creek Falls",
    meta: "Grand Staircase-Escalante · ~6 mi round trip",
    blurb: "A hike along Scenic Byway 12 to a 130-ft waterfall and swimming hole.",
    tags: [],
    done: false,
  },
  {
    id: "spring-kodachrome",
    section: "spring",
    title: "Kodachrome Basin State Park",
    meta: "Easy trails",
    blurb: "Colorful sandstone spires with approachable, easy trails.",
    tags: [],
    done: false,
  },
  {
    id: "spring-cottonwoodhikes",
    section: "spring",
    title: "Cottonwood Canyon hikes as snow melts",
    meta: "Red Pine Lake · White Pine Lake · Donut Falls · Silver Lake",
    blurb: "Four hikes to rotate through as the Cottonwoods thaw out.",
    tags: [],
    done: false,
  },
  {
    id: "spring-templevisit",
    section: "spring",
    title: "Use your Temple open house tickets",
    meta: "If you booked them in September",
    blurb: "Prime season to actually use the reservation from the \"Do This Now\" list.",
    tags: [],
    done: false,
  },

  // ---------- Early Summer 2027 ----------
  {
    id: "summer-cecretlake",
    section: "summer",
    title: "Cecret Lake / Albion Basin",
    meta: "Easy 1.7 mi · peak bloom mid-July–early Aug",
    blurb: "Peak wildflowers land just past the June cutoff — an early-June visit still catches part of the bloom, with full bloom following a few weeks later.",
    tags: ["stretch"],
    done: false,
  },
  {
    id: "summer-timpanogos",
    section: "summer",
    title: "Mount Timpanogos summit",
    meta: "~14+ mi, strenuous but non-technical",
    blurb: "Waterfalls, wildflowers, mountain goats. Weekend permits are required July–October — just after this window — so plan this as an early, permit-free weekday summit attempt.",
    tags: ["stretch", "permit"],
    done: false,
  },
  {
    id: "summer-millcreek",
    section: "summer",
    title: "Millcreek Canyon hikes",
    meta: "Grandeur Peak · Dog Lake",
    blurb: "Close to town, and dog-friendly on the right days.",
    tags: [],
    done: false,
  },
  {
    id: "summer-snowcanyon",
    section: "summer",
    title: "Snow Canyon State Park",
    meta: "Near St. George",
    blurb: "Worth folding in if you swing south again before June.",
    tags: [],
    done: false,
  },
  {
    id: "summer-saltflats",
    section: "summer",
    title: "Bonneville Salt Flats + Spiral Jetty + Sun Tunnels",
    meta: "West desert day trip · dry conditions only",
    blurb: "Drive on the salt, then pair it with the Spiral Jetty and Sun Tunnels land-art installations for a full \"weird Utah\" day. Note: Spiral Jetty's shoreline has shifted with historically low Great Salt Lake levels — check current conditions.",
    tags: [],
    done: false,
  },

  // ---------- Anytime / local culture ----------
  {
    id: "anytime-templesquare",
    section: "anytime",
    title: "Temple Square beyond the temple",
    meta: "New Visitors' Center opened May 2026",
    blurb: "The free \"Inside a Temple\" replica tour, Tabernacle organ recitals, and the Church History Museum.",
    tags: [],
    done: false,
  },
  {
    id: "anytime-food",
    section: "anytime",
    title: "SLC food scene",
    meta: "Log Haven · Takashi · Red Iguana · Pretty Bird · HSL · The Copper Onion",
    blurb: "A running list of SLC's best-regarded restaurants across cuisines.",
    tags: [],
    done: false,
  },
  {
    id: "anytime-breweries",
    section: "anytime",
    title: "Brewery crawl",
    meta: "Fisher · Squatters · Red Rock · Epic · Level Crossing · SaltFire · Bewilder",
    blurb: "Seven breweries worth working through at your own pace.",
    tags: [],
    done: false,
  },
  {
    id: "anytime-moabdrives",
    section: "anytime",
    title: "Moab scenic drives beyond Arches",
    meta: "Potash Road · Scenic Byway 128 · La Sal Mountain Loop",
    blurb: "Potash Road (Byway 279), Scenic Byway 128 along the Colorado River (arguably the best river drive in the state), the La Sal Mountain Loop, and a guided non-technical Jeep tour of the Shafer Trail.",
    tags: [],
    done: false,
  },
  {
    id: "anytime-bisonroundup",
    section: "anytime",
    title: "Antelope Island Bison Roundup",
    meta: "Late October · distinct from a regular visit",
    blurb: "A specific annual event, separate from just visiting the island — worth catching if you haven't.",
    tags: ["annual"],
    done: false,
  },
  {
    id: "anytime-farflung",
    section: "anytime",
    title: "Natural Bridges · Dinosaur National Monument · Timpanogos Cave",
    meta: "Further-flung monuments",
    blurb: "Three monuments that haven't come up elsewhere on the list.",
    tags: [],
    done: false,
  },
  {
    id: "anytime-hiddengems",
    section: "anytime",
    title: "Hidden gems",
    meta: "Statewide oddities",
    blurb: "Fantasy Canyon and Moonshine Arch (near Vernal), Meadow Hot Springs, Devil's Slide, the Bingham Canyon Mine overlook, Valley of the Gods / Moki Dugway in the far southeast, and the quirky small town of Helper.",
    tags: [],
    done: false,
  },
  {
    id: "anytime-darksky",
    section: "anytime",
    title: "Dark-sky stargazing",
    meta: "Natural Bridges · Dead Horse Point · Cedar Breaks · North Fork Park",
    blurb: "North Fork Park near Ogden is the closest-in option; the others double up with parks already on this list.",
    tags: [],
    done: false,
  },
];
